- name: Install NFS server
  tags:
    - nfs_server
  when: ansible_distribution == 'CentOS'
  yum:
    name:
      - nfs-utils
    state: installed

- name: Start NFS server service
  tags:
    - nfs_server
  when: ansible_distribution == 'CentOS'
  action: service name={{item}} state=started
  with_items:
    - rpcbind
    - nfslock
    - nfs

- name: Add ports to firewalld
  tags:
    - nfs_server
  when: ansible_distribution == 'CentOS'
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - nfs
    - nfs3
    - rpc-bind

- name: Reload firewalld
  service: name=firewalld state=restarted
