- name: Install NFS server
  when: ansible_distribution == 'CentOS'
  tags:
    - nfs_server
  yum:
    name:
      - nfs-utils
    state: installed

- name: Start NFS server service
  when: ansible_distribution == 'CentOS'
  action: service name={{item}} state=started
  tags:
    - nfs_server
  with_items:
    - rpcbind
    - nfslock
    - nfs

- name: Add ports to firewalld
  when: ansible_distribution == 'CentOS'
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - nfs
    - nfs3
    - rpc-bind
